### ISSUE TITLE
libcocos2d Mac doesn't build on branch 3.15

### ISSUE THREAD

**Issue by crookedbard** [xpams/cocos2d-x-for-tvOS#2]
libcocos2d Mac doesn't build.
CCGLViewImpl-desktop.cpp
Line 600: glfwSetWindowMonitor - use of undeclared identifier
Line 613: GLFW_DONT_CARE - use of undeclared identifier

**Comment by xpams** [comment]
take the latest changes from branch 3.15
https://github.com/xpams/cocos2d-x-for-tvOS/commit/6788344eca266f953595df032cad30c200705656
